// tslint:disable
/**
 * portal
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface InDdcSearchControllerSearchTransferBlock
 */
export interface InDdcSearchControllerSearchTransferBlock {
  /**
   * DDC 流转记录ID
   * @type {string}
   * @memberof InDdcSearchControllerSearchTransferBlock
   */
  ddcTransferId: string;
}
/**
 *
 * @export
 * @interface InDdcSearchControllerDetail
 */
export interface InDdcSearchControllerDetail {
  /**
   * 平台DDC ID
   * @type {string}
   * @memberof InDdcSearchControllerDetail
   */
  platformDdcId: string;
}
/**
 *
 * @export
 * @interface RequestPageInfoInDdcSearchControllerDetail
 */
export interface RequestPageInfoInDdcSearchControllerDetail {
  /**
   *
   * @type {InDdcSearchControllerDetail}
   * @memberof RequestPageInfoInDdcSearchControllerDetail
   */
  data: InDdcSearchControllerDetail;
  /**
   *
   * @type {InPage}
   * @memberof RequestPageInfoInDdcSearchControllerDetail
   */
  page: InPage;
}
/**
 *
 * @export
 * @interface RequestPageInfoInDdcSearchControllerSearchesDdc
 */
export interface RequestPageInfoInDdcSearchControllerSearchesDdc {
  /**
   *
   * @type {InDdcSearchControllerSearchesDdc}
   * @memberof RequestPageInfoInDdcSearchControllerSearchesDdc
   */
  data: InDdcSearchControllerSearchesDdc;
  /**
   *
   * @type {InPage}
   * @memberof RequestPageInfoInDdcSearchControllerSearchesDdc
   */
  page: InPage;
}
/**
 *
 * @export
 * @interface RequestPageInfoInDdcSearchControllerSearchesTransfer
 */
export interface RequestPageInfoInDdcSearchControllerSearchesTransfer {
  /**
   *
   * @type {InDdcSearchControllerSearchesTransfer}
   * @memberof RequestPageInfoInDdcSearchControllerSearchesTransfer
   */
  data: InDdcSearchControllerSearchesTransfer;
  /**
   *
   * @type {InPage}
   * @memberof RequestPageInfoInDdcSearchControllerSearchesTransfer
   */
  page: InPage;
}
/**
 *
 * @export
 * @interface ResultInfoOutDdcSearchControllerDdcDetail
 */
export interface ResultInfoOutDdcSearchControllerDdcDetail {
  /**
   * 成功：0，失败：-1
   * @type {number}
   * @memberof ResultInfoOutDdcSearchControllerDdcDetail
   */
  code: number;
  /**
   *
   * @type {OutDdcSearchControllerDdcDetail}
   * @memberof ResultInfoOutDdcSearchControllerDdcDetail
   */
  data?: OutDdcSearchControllerDdcDetail;
  /**
   * 此标记同时写入到日志文件中，方便查找
   * @type {string}
   * @memberof ResultInfoOutDdcSearchControllerDdcDetail
   */
  errorLogCode: string;
  /**
   * 都是消息编码，前端自行国际化处理
   * @type {string}
   * @memberof ResultInfoOutDdcSearchControllerDdcDetail
   */
  message: string;
}
/**
 *
 * @export
 * @interface ResultInfoOutDdcSearchControllerSearchTransferBlock
 */
export interface ResultInfoOutDdcSearchControllerSearchTransferBlock {
  /**
   * 成功：0，失败：-1
   * @type {number}
   * @memberof ResultInfoOutDdcSearchControllerSearchTransferBlock
   */
  code: number;
  /**
   *
   * @type {OutDdcSearchControllerSearchTransferBlock}
   * @memberof ResultInfoOutDdcSearchControllerSearchTransferBlock
   */
  data?: OutDdcSearchControllerSearchTransferBlock;
  /**
   * 此标记同时写入到日志文件中，方便查找
   * @type {string}
   * @memberof ResultInfoOutDdcSearchControllerSearchTransferBlock
   */
  errorLogCode: string;
  /**
   * 都是消息编码，前端自行国际化处理
   * @type {string}
   * @memberof ResultInfoOutDdcSearchControllerSearchTransferBlock
   */
  message: string;
}
/**
 *
 * @export
 * @interface ResultInfoPageListOutDdcSearchControllerDdcOwnerDetail
 */
export interface ResultInfoPageListOutDdcSearchControllerDdcOwnerDetail {
  /**
   * 成功：0，失败：-1
   * @type {number}
   * @memberof ResultInfoPageListOutDdcSearchControllerDdcOwnerDetail
   */
  code: number;
  /**
   *
   * @type {Array<OutDdcSearchControllerDdcOwnerDetail>}
   * @memberof ResultInfoPageListOutDdcSearchControllerDdcOwnerDetail
   */
  data?: Array<OutDdcSearchControllerDdcOwnerDetail>;
  /**
   * 此标记同时写入到日志文件中，方便查找
   * @type {string}
   * @memberof ResultInfoPageListOutDdcSearchControllerDdcOwnerDetail
   */
  errorLogCode: string;
  /**
   * 都是消息编码，前端自行国际化处理
   * @type {string}
   * @memberof ResultInfoPageListOutDdcSearchControllerDdcOwnerDetail
   */
  message: string;
  /**
   *
   * @type {PageInfo}
   * @memberof ResultInfoPageListOutDdcSearchControllerDdcOwnerDetail
   */
  resultPageInfo?: PageInfo;
}
/**
 *
 * @export
 * @interface OutDdcSearchControllerSearchesDdc
 */
export interface OutDdcSearchControllerSearchesDdc {
  /**
   * DDC ID
   * @type {string}
   * @memberof OutDdcSearchControllerSearchesDdc
   */
  ddcId: string;
  /**
   * DDC 名称
   * @type {string}
   * @memberof OutDdcSearchControllerSearchesDdc
   */
  ddcName: string;
  /**
   * DDC 所有者
   * @type {string}
   * @memberof OutDdcSearchControllerSearchesDdc
   */
  ddcOwner: string;
  /**
   * DDC 所有者
   * @type {string}
   * @memberof OutDdcSearchControllerSearchesDdc
   */
  ddcOwners: string;
  /**
   * DDC 发行总数量  1155数量      721为1
   * @type {number}
   * @memberof OutDdcSearchControllerSearchesDdc
   */
  ddcPubTotal: number;
  /**
   * DDC 状态  1=正常  2=销毁  默认0
   * @type {number}
   * @memberof OutDdcSearchControllerSearchesDdc
   */
  ddcState: number;
  /**
   * DDC 符号
   * @type {string}
   * @memberof OutDdcSearchControllerSearchesDdc
   */
  ddcSymbol: string;
  /**
   * DDC 类型 721=721合约   1155=1155合约   默认0
   * @type {number}
   * @memberof OutDdcSearchControllerSearchesDdc
   */
  ddcType: number;
  /**
   * DDC URI
   * @type {string}
   * @memberof OutDdcSearchControllerSearchesDdc
   */
  ddcUri?: string;
  /**
   * DDC生成时间
   * @type {object}
   * @memberof OutDdcSearchControllerSearchesDdc
   */
  generateDate?: object;
  /**
   * 开放联盟链框架ID
   * @type {number}
   * @memberof OutDdcSearchControllerSearchesDdc
   */
  opbChainId?: number;
  /**
   * 开放联盟链框架名称
   * @type {string}
   * @memberof OutDdcSearchControllerSearchesDdc
   */
  opcChainName?: string;
  /**
   * DDC 运营管理状态   1=冻结  2=正常（解冻）    默认0
   * @type {number}
   * @memberof OutDdcSearchControllerSearchesDdc
   */
  opsMgrState: number;
  /**
   * 平台DDC ID
   * @type {string}
   * @memberof OutDdcSearchControllerSearchesDdc
   */
  platformDdcId: string;
  /**
   * 平台方
   * @type {string}
   * @memberof OutDdcSearchControllerSearchesDdc
   */
  platformName: string;
}
/**
 *
 * @export
 * @interface ResultInfoPageListOutDdcSearchControllerSearchesDdc
 */
export interface ResultInfoPageListOutDdcSearchControllerSearchesDdc {
  /**
   * 成功：0，失败：-1
   * @type {number}
   * @memberof ResultInfoPageListOutDdcSearchControllerSearchesDdc
   */
  code: number;
  /**
   *
   * @type {Array<OutDdcSearchControllerSearchesDdc>}
   * @memberof ResultInfoPageListOutDdcSearchControllerSearchesDdc
   */
  data?: Array<OutDdcSearchControllerSearchesDdc>;
  /**
   * 此标记同时写入到日志文件中，方便查找
   * @type {string}
   * @memberof ResultInfoPageListOutDdcSearchControllerSearchesDdc
   */
  errorLogCode: string;
  /**
   * 都是消息编码，前端自行国际化处理
   * @type {string}
   * @memberof ResultInfoPageListOutDdcSearchControllerSearchesDdc
   */
  message: string;
  /**
   *
   * @type {PageInfo}
   * @memberof ResultInfoPageListOutDdcSearchControllerSearchesDdc
   */
  resultPageInfo?: PageInfo;
}
/**
 *
 * @export
 * @interface ResultInfoPageListOutDdcSearchControllerSearchesTransfer
 */
export interface ResultInfoPageListOutDdcSearchControllerSearchesTransfer {
  /**
   * 成功：0，失败：-1
   * @type {number}
   * @memberof ResultInfoPageListOutDdcSearchControllerSearchesTransfer
   */
  code: number;
  /**
   *
   * @type {Array<OutDdcSearchControllerSearchesTransfer>}
   * @memberof ResultInfoPageListOutDdcSearchControllerSearchesTransfer
   */
  data?: Array<OutDdcSearchControllerSearchesTransfer>;
  /**
   * 此标记同时写入到日志文件中，方便查找
   * @type {string}
   * @memberof ResultInfoPageListOutDdcSearchControllerSearchesTransfer
   */
  errorLogCode: string;
  /**
   * 都是消息编码，前端自行国际化处理
   * @type {string}
   * @memberof ResultInfoPageListOutDdcSearchControllerSearchesTransfer
   */
  message: string;
  /**
   *
   * @type {PageInfo}
   * @memberof ResultInfoPageListOutDdcSearchControllerSearchesTransfer
   */
  resultPageInfo?: PageInfo;
}
